[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true
fs_permissions = [{ access = "read", path = "./" }]
remappings = [
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
